name: Train and Deploy Faces Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset from Google Drive
        run: |
          gdown --id 14ggF8_oQ-viIQD-njwpx9AaWCrAlMw3_
          tar -xzvf caras_fotos.tgz

      - name: Execute model training
        run: |
          echo "Running model training..."
          python faces_model.py

      - name: Verify model training output
        run: |
          echo "Verifying model output..."
          if [ ! -f "faces-model/saved_model.pb" ]; then
            echo "Error: saved_model.pb not found!"
            exit 1
          fi
          echo "Model saved_model.pb found successfully."

      - name: Prepare versioned model directory
        run: |
          echo "Preparing versioned model directory..."
          rm -rf faces-model/1
          mkdir -p faces-model/1
          cp -r faces-model/* faces-model/1/
          echo "Versioned directory contents:"
          ls -R faces-model/1/

      - name: Validate model directory
        run: |
          echo "Validating model directory..."
          ls -R faces-model/

      - name: Download and run the Docker base image
        run: docker run -d --name serving_base tensorflow/serving

      - name: Copy model to the Docker container
        run: |
          echo "Copying model to Docker container..."
          docker cp faces-model/1/ serving_base:/models/model_faces

      - name: Build custom Docker image
        run: |
          echo "Building Docker image..."
          docker commit --change "ENV MODEL_NAME model_faces" serving_base ${{ secrets.DOCKER_USER }}/tensorflow-model_faces:${{ github.sha }}

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Logging into DockerHub..."
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Push
        run: |
          echo "Pushing Docker image to DockerHub..."
          docker push ${{ secrets.DOCKER_USER }}/tensorflow-model_faces:${{ github.sha }}
